from openpyxl import Workbook, load_workbook

print('Mouse info')
mouse_number = input("Input Mouse Number: ")
weight = float(input("Input Mouse weight: "))
print('Day 1')
day1_v_i = float(input("Input Day 1 Initial Volume: "))
day1_v_f = float(input("Input Day 1 Final Volume: "))
day1_dc1_i = float(input('Input Day 1 DC1 Initial: '))
day1_dc1_f = float(input('Input Day 1 DC1 Final: '))
day1_dc2_i = float(input('Input Day 1 DC2 Initial: '))
day1_dc2_f = float(input('Input Day 1 DC2 Initial: '))
print('Day 2')
day2_v_i = float(input('Input Day 2 Initial Volume: '))
day2_v_f = float(input('Input Day 2 Final Volume:'))
day2_dc1_i = float(input('Input Day 2 DC1 Initial: '))
day2_dc1_f = float(input('Input Day 2 DC1 Final: '))
day2_dc2_i = float(input('Input Day 2 DC2 Initial: '))
day2_dc2_f = float(input('Input Day 2 DC2 Final: '))
print('Day 3')
day3_v_i = float(input('Input Day 3 Volume Initial:'))
day3_v_f = float(input('Input Day 3 Volume Final: '))
day3_dc1_i = float(input('Input Day 3 DC1 Initial: '))
day3_dc1_f = float(input('Input Day 3 DC1 Final: '))
day3_dc2_i = float(input('Input Day 3 DC2 Initial: '))
day3_dc2_f = float(input('Input Day 3 DC2 Final: '))
print('Day 4')
day4_v_i = float(input('Input Day 4 Volume Initial: '))
day4_v_f = float(input('Input Day 4 Volume Final: '))
day4_dc1_i = float(input('Input Day 4 DC1 Initial: '))
day4_dc1_f = float(input('Input Day 4 DC1 Final: '))
day4_dc2_i = float(input('Input Day 4 DC2 Initial: '))
day4_dc2_f = float(input('Input Day4 DC2 Final: '))


wb = load_workbook('/Users/cmason/Downloads/did_test.xlsx')
ws = wb.active
ws.append([mouse_number, weight, day1_v_i, day1_v_f, day1_dc1_i, day1_dc2_i, day1_dc2_f])
wb.save('/Users/cmason/Downloads/did_test2.xlsx')