# #y = {'mouse_number': 1, 'wgt': 2.0, 'D1VI': 3.0, 'D2VI': 4.0, 'D3VI': 5.0, 'D4VI': 6.0, 'D1VF': 7.0, 'D2VF': 8.0,
#      'D3VF': 9.0, 'D4VF': 10.0, 'D1DC1I':11.0, 'D2DC1I': 12.0, 'D3DC1I': 13.0, 'D4DC1I': 14.0, 'D1DC1F': 15.0,
#      'D2DC1F': 16.0, 'D3DC1F': 17.0, 'D4DC1F': 18.0, 'D1DC2I': 19.0, 'D2DC2I': 20.0, 'D3DC2I': 21.0, 'D4DC2I': 22.0,
#      'D1DC2F': 23.0, 'D2DC2F': 24.0, 'D3DC2F': 25.0, 'D4DC2F': 26.0}
# res = {}
# for key, value in range(26):
#
#
# print(res)
